import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rename, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const sourceUrl = "https://openapi.tossinvest.com/openapi-docs/latest/openapi.json";
const packageRoot = fileURLToPath(new URL("../", import.meta.url));

const response = await fetch(sourceUrl, {
  headers: { accept: "application/json" },
  signal: AbortSignal.timeout(30_000),
});

if (!response.ok) {
  throw new Error(`토스증권 OpenAPI를 가져오지 못했습니다: HTTP ${response.status}`);
}

const spec = await response.json();
if (spec.openapi !== "3.1.0" || typeof spec.info?.version !== "string" || !spec.paths) {
  throw new Error("토스증권 OpenAPI 형식이 예상과 다릅니다.");
}

const operations = Object.entries(spec.paths).flatMap(([path, pathItem]) =>
  Object.entries(pathItem)
    .filter(
      ([method, operation]) =>
        ["get", "post", "put", "patch", "delete"].includes(method) && operation?.operationId,
    )
    .map(([method, operation]) => ({
      operationId: operation.operationId,
      method: method.toUpperCase(),
      path,
      summary: operation.summary ?? operation.operationId,
      tag: operation.tags?.[0] ?? "Other",
      mutatesAccount:
        ["post", "put", "patch", "delete"].includes(method) && path !== "/oauth2/token",
    })),
);

if (
  operations.length === 0 ||
  new Set(operations.map(({ operationId }) => operationId)).size !== operations.length
) {
  throw new Error("토스증권 OpenAPI operationId가 없거나 중복되었습니다.");
}

const header = `// Generated by scripts/sync-openapi.mjs from ${sourceUrl}.\n// Do not edit manually.\n`;
const manifest = `${header}\nexport const TOSS_OPENAPI_VERSION = ${JSON.stringify(spec.info.version)} as const;\n\nexport const TOSS_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;\n\nexport type TossOperation = (typeof TOSS_OPERATIONS)[number];\nexport type TossOperationId = TossOperation["operationId"];\n`;

await mkdir(join(packageRoot, "openapi"), { recursive: true });
await mkdir(join(packageRoot, "src/generated"), { recursive: true });
const temporaryDirectory = await mkdtemp(join(packageRoot, ".openapi-sync-"));

try {
  const temporarySpec = join(temporaryDirectory, "openapi.json");
  const temporaryManifest = join(temporaryDirectory, "operations.ts");
  const temporarySchema = join(temporaryDirectory, "schema.ts");

  await writeFile(temporarySpec, `${JSON.stringify(spec, null, 2)}\n`);
  await writeFile(temporaryManifest, manifest);
  await execFileAsync(
    "pnpm",
    [
      "exec",
      "openapi-typescript",
      temporarySpec,
      "-o",
      temporarySchema,
      "--immutable",
      "--export-type",
    ],
    { cwd: packageRoot, maxBuffer: 10 * 1024 * 1024 },
  );
  await execFileAsync(
    "pnpm",
    ["exec", "prettier", "--write", temporarySpec, temporaryManifest, temporarySchema],
    { cwd: packageRoot, maxBuffer: 10 * 1024 * 1024 },
  );

  await Promise.all([
    rename(temporarySpec, join(packageRoot, "openapi/openapi.json")),
    rename(temporaryManifest, join(packageRoot, "src/generated/operations.ts")),
    rename(temporarySchema, join(packageRoot, "src/generated/schema.ts")),
  ]);
} finally {
  await rm(temporaryDirectory, { force: true, recursive: true });
}

console.log(`토스증권 OpenAPI ${spec.info.version}: ${operations.length}개 operation 동기화 완료`);
