import { execFile } from "node:child_process";
import { readFile, mkdir, mkdtemp, rename, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
export const TOSS_OPENAPI_SOURCE =
  "https://openapi.tossinvest.com/openapi-docs/latest/openapi.json";
const packageRoot = fileURLToPath(new URL("../", import.meta.url));
const httpMethods = new Set(["get", "post", "put", "patch", "delete"]);
const knownRateLimitGroups = new Set([
  "AUTH",
  "MARKET_DATA",
  "MARKET_DATA_CHART",
  "STOCK",
  "MARKET_INFO",
  "RANKING",
  "MARKET_INDICATOR",
  "MARKET_INDICATOR_CHART",
  "ACCOUNT",
  "ASSET",
  "ORDER_HISTORY",
  "ORDER",
  "CONDITIONAL_ORDER_HISTORY",
  "CONDITIONAL_ORDER",
  "ORDER_INFO",
]);

export function parseRateLimitGroup(description) {
  if (typeof description !== "string") return null;
  const match = description.match(/\*\*Rate Limits Group\*\*:\s*`([^`]+)`/);
  return match?.[1] ?? null;
}

export function buildOperations(spec) {
  assertSupportedSpec(spec);
  const operations = [];

  for (const [path, pathItem] of Object.entries(spec.paths)) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!httpMethods.has(method)) continue;
      if (!operation || typeof operation !== "object" || !operation.operationId) {
        throw new Error(`${method.toUpperCase()} ${path} operationId가 없습니다.`);
      }

      const rateLimitGroup = parseRateLimitGroup(operation.description);
      if (path === "/oauth2/token") {
        if (rateLimitGroup !== null && rateLimitGroup !== "AUTH") {
          throw new Error(
            `${operation.operationId} OAuth Rate Limits Group은 AUTH 또는 null이어야 합니다.`,
          );
        }
      } else if (rateLimitGroup === null) {
        throw new Error(`${operation.operationId} 업무 operation의 Rate Limits Group이 없습니다.`);
      }

      if (rateLimitGroup !== null && !knownRateLimitGroups.has(rateLimitGroup)) {
        throw new Error(
          `${operation.operationId}의 알 수 없는 Rate Limits Group입니다: ${rateLimitGroup}`,
        );
      }

      operations.push({
        operationId: operation.operationId,
        method: method.toUpperCase(),
        path,
        summary: operation.summary ?? operation.operationId,
        tag: operation.tags?.[0] ?? "Other",
        rateLimitGroup,
        mutatesAccount:
          ["post", "put", "patch", "delete"].includes(method) && path !== "/oauth2/token",
      });
    }
  }

  if (
    operations.length === 0 ||
    new Set(operations.map(({ operationId }) => operationId)).size !== operations.length
  ) {
    throw new Error("토스증권 OpenAPI operationId가 없거나 중복되었습니다.");
  }

  return operations;
}

export async function syncOpenApi({ source = TOSS_OPENAPI_SOURCE, check = false } = {}) {
  const spec = await loadSpec(source);
  const operations = buildOperations(spec);
  const header = `// Generated by scripts/sync-openapi.mjs from ${TOSS_OPENAPI_SOURCE}.\n// Do not edit manually.\n`;
  const manifest = `${header}\nexport const TOSS_OPENAPI_VERSION = ${JSON.stringify(spec.info.version)} as const;\n\nexport const TOSS_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;\n\nexport type TossOperation = (typeof TOSS_OPERATIONS)[number];\nexport type TossOperationId = TossOperation["operationId"];\nexport type TossRateLimitGroup = NonNullable<TossOperation["rateLimitGroup"]>;\n`;

  await mkdir(join(packageRoot, "openapi"), { recursive: true });
  await mkdir(join(packageRoot, "src/generated"), { recursive: true });
  const temporaryDirectory = await mkdtemp(join(packageRoot, ".openapi-sync-"));

  try {
    const temporarySpec = join(temporaryDirectory, "openapi.json");
    const temporaryManifest = join(temporaryDirectory, "operations.ts");
    const temporarySchema = join(temporaryDirectory, "schema.ts");

    await writeFile(temporarySpec, `${JSON.stringify(spec, null, 2)}\n`);
    await writeFile(temporaryManifest, manifest);
    await execFileAsync(
      "pnpm",
      [
        "exec",
        "openapi-typescript",
        temporarySpec,
        "-o",
        temporarySchema,
        "--immutable",
        "--export-type",
      ],
      { cwd: packageRoot, maxBuffer: 10 * 1024 * 1024 },
    );
    await execFileAsync(
      "pnpm",
      ["exec", "prettier", "--write", temporarySpec, temporaryManifest, temporarySchema],
      { cwd: packageRoot, maxBuffer: 10 * 1024 * 1024 },
    );

    const generatedFiles = [
      [temporarySpec, join(packageRoot, "openapi/openapi.json")],
      [temporaryManifest, join(packageRoot, "src/generated/operations.ts")],
      [temporarySchema, join(packageRoot, "src/generated/schema.ts")],
    ];
    if (check) {
      const changedFiles = [];
      for (const [temporaryFile, targetFile] of generatedFiles) {
        const [generated, current] = await Promise.all([
          readFile(temporaryFile),
          readFile(targetFile).catch(() => null),
        ]);
        if (!current || !generated.equals(current)) changedFiles.push(targetFile);
      }
      if (changedFiles.length > 0) {
        throw new Error(
          `고정 OpenAPI 스냅샷과 생성물이 일치하지 않습니다: ${changedFiles.join(", ")}`,
        );
      }
    } else {
      await Promise.all(
        generatedFiles.map(([temporaryFile, targetFile]) => rename(temporaryFile, targetFile)),
      );
    }
  } finally {
    await rm(temporaryDirectory, { force: true, recursive: true });
  }

  console.log(
    `토스증권 OpenAPI ${spec.info.version}: ${operations.length}개 operation ${
      check ? "동기화 확인 완료" : "동기화 완료"
    }`,
  );
}

async function loadSpec(source) {
  if (/^https?:\/\//.test(source)) {
    const response = await fetch(source, {
      headers: { accept: "application/json" },
      signal: AbortSignal.timeout(30_000),
    });
    if (!response.ok) {
      throw new Error(`토스증권 OpenAPI를 가져오지 못했습니다: HTTP ${response.status}`);
    }
    return response.json();
  }

  return JSON.parse(await readFile(resolve(process.cwd(), source), "utf8"));
}

function assertSupportedSpec(spec) {
  if (spec?.openapi !== "3.1.0" || typeof spec.info?.version !== "string" || !spec.paths) {
    throw new Error("토스증권 OpenAPI 형식이 예상과 다릅니다.");
  }
}

function parseArguments(arguments_) {
  let source = TOSS_OPENAPI_SOURCE;
  let check = false;
  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];
    if (argument === "--check") {
      check = true;
      continue;
    }
    if (argument === "--source") {
      const value = arguments_[index + 1];
      if (!value) throw new Error("--source 값이 필요합니다.");
      source = value;
      index += 1;
      continue;
    }
    throw new Error(`알 수 없는 인자입니다: ${argument}`);
  }
  return { source, check };
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  await syncOpenApi(parseArguments(process.argv.slice(2)));
}
